POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NasdasdVCJ9.eyJ1c2VybmFtZSI6InNhbXBhbnNzaSIsImlkIjoiNjQ4MmZkZmNiODkzYjUwMTllMmZkMDY5IiwiaWF0IjoxNjg2MzMzOTA1LCJleHAiOjE2ODYzMzc1MDV9.jRxP6DNVoDusocgAwbd5k2gLMLED16vXHJERKPnsjng

{
    "title": "sampanssiblogi nro 2",
    "author": "2",
    "url": "urlir.com",
    "likes": 2
}